// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package racer_http

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, first_name, last_name, email, created_at FROM user WHERE id = ?
`

type GetUserRow struct {
	ID        int64
	FirstName string
	LastName  string
	Email     string
	CreatedAt string
}

func (q *Queries) GetUser(ctx context.Context, id int64) (GetUserRow, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
