// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package entities

import (
	"database/sql"
)

type Event struct {
	ID           int64
	LocationID   int64
	Type         string
	Date         string
	TotalDrivers int64
}

type EventResult struct {
	ID             int64
	EventID        int64
	UserID         int64
	BestLapTime    int64
	AverageLapTime int64
	Position       int64
	NumberOfLaps   int64
}

type Location struct {
	ID   int64
	Name string
}

type User struct {
	ID        int64
	FirstName string
	LastName  string
	Email     string
	Password  string
	CreatedAt sql.NullString
}
