// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package entities

import (
	"context"
	"database/sql"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO event (location_id, type, date, total_drivers) VALUES (?, ?, ?, ?)
    RETURNING id, location_id, type, date, total_drivers
`

type CreateEventParams struct {
	LocationID   int64
	Type         string
	Date         string
	TotalDrivers int64
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.LocationID,
		arg.Type,
		arg.Date,
		arg.TotalDrivers,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Type,
		&i.Date,
		&i.TotalDrivers,
	)
	return i, err
}

const createEventResult = `-- name: CreateEventResult :one
INSERT INTO event_result (event_id, user_id, best_lap_time, average_lap_time, position, number_of_laps) VALUES (?, ?, ?, ?, ?, ?)
    RETURNING id, event_id, user_id, best_lap_time, average_lap_time, position, number_of_laps
`

type CreateEventResultParams struct {
	EventID        int64
	UserID         int64
	BestLapTime    int64
	AverageLapTime int64
	Position       int64
	NumberOfLaps   int64
}

func (q *Queries) CreateEventResult(ctx context.Context, arg CreateEventResultParams) (EventResult, error) {
	row := q.db.QueryRowContext(ctx, createEventResult,
		arg.EventID,
		arg.UserID,
		arg.BestLapTime,
		arg.AverageLapTime,
		arg.Position,
		arg.NumberOfLaps,
	)
	var i EventResult
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.BestLapTime,
		&i.AverageLapTime,
		&i.Position,
		&i.NumberOfLaps,
	)
	return i, err
}

const createLocation = `-- name: CreateLocation :one
INSERT INTO location (name) VALUES (?)
    RETURNING id, name
`

func (q *Queries) CreateLocation(ctx context.Context, name string) (Location, error) {
	row := q.db.QueryRowContext(ctx, createLocation, name)
	var i Location
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO user (first_name, last_name, email, password) VALUES (?, ?, ?, ?)
    RETURNING first_name, last_name, email, created_at
`

type CreateUserParams struct {
	FirstName string
	LastName  string
	Email     string
	Password  string
}

type CreateUserRow struct {
	FirstName string
	LastName  string
	Email     string
	CreatedAt sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getEventByLocationAndTypeAndDate = `-- name: GetEventByLocationAndTypeAndDate :one
SELECT id, location_id, type, date, total_drivers FROM event WHERE location_id = ? AND type = ? AND date = ?
`

type GetEventByLocationAndTypeAndDateParams struct {
	LocationID int64
	Type       string
	Date       string
}

func (q *Queries) GetEventByLocationAndTypeAndDate(ctx context.Context, arg GetEventByLocationAndTypeAndDateParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByLocationAndTypeAndDate, arg.LocationID, arg.Type, arg.Date)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.LocationID,
		&i.Type,
		&i.Date,
		&i.TotalDrivers,
	)
	return i, err
}

const getEventResultByEventIdAndUserId = `-- name: GetEventResultByEventIdAndUserId :one
SELECT id, event_id, user_id, best_lap_time, average_lap_time, position, number_of_laps FROM event_result WHERE event_id = ? and user_id = ?
`

type GetEventResultByEventIdAndUserIdParams struct {
	EventID int64
	UserID  int64
}

func (q *Queries) GetEventResultByEventIdAndUserId(ctx context.Context, arg GetEventResultByEventIdAndUserIdParams) (EventResult, error) {
	row := q.db.QueryRowContext(ctx, getEventResultByEventIdAndUserId, arg.EventID, arg.UserID)
	var i EventResult
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.BestLapTime,
		&i.AverageLapTime,
		&i.Position,
		&i.NumberOfLaps,
	)
	return i, err
}

const getEventsByUser = `-- name: GetEventsByUser :many
SELECT event.id, event.location_id, event.type, event.date, event.total_drivers, location.id, location.name, event_result.id, event_result.event_id, event_result.user_id, event_result.best_lap_time, event_result.average_lap_time, event_result.position, event_result.number_of_laps FROM event
    LEFT JOIN location on event.location_id = location.id
    LEFT JOIN event_result on event.id = event_result.event_id
    WHERE event_result.user_id = ?
`

type GetEventsByUserRow struct {
	Event       Event
	Location    Location
	EventResult EventResult
}

func (q *Queries) GetEventsByUser(ctx context.Context, userID int64) ([]GetEventsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getEventsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsByUserRow
	for rows.Next() {
		var i GetEventsByUserRow
		if err := rows.Scan(
			&i.Event.ID,
			&i.Event.LocationID,
			&i.Event.Type,
			&i.Event.Date,
			&i.Event.TotalDrivers,
			&i.Location.ID,
			&i.Location.Name,
			&i.EventResult.ID,
			&i.EventResult.EventID,
			&i.EventResult.UserID,
			&i.EventResult.BestLapTime,
			&i.EventResult.AverageLapTime,
			&i.EventResult.Position,
			&i.EventResult.NumberOfLaps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationByName = `-- name: GetLocationByName :one
SELECT id, name FROM location WHERE name = ?
`

func (q *Queries) GetLocationByName(ctx context.Context, name string) (Location, error) {
	row := q.db.QueryRowContext(ctx, getLocationByName, name)
	var i Location
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, first_name, last_name, email FROM user WHERE email = ?
`

type GetUserByEmailRow struct {
	ID        int64
	FirstName string
	LastName  string
	Email     string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
	)
	return i, err
}

const getUserByEmailForLogin = `-- name: GetUserByEmailForLogin :one
SELECT id, email, password FROM user WHERE email = ?
`

type GetUserByEmailForLoginRow struct {
	ID       int64
	Email    string
	Password string
}

func (q *Queries) GetUserByEmailForLogin(ctx context.Context, email string) (GetUserByEmailForLoginRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailForLogin, email)
	var i GetUserByEmailForLoginRow
	err := row.Scan(&i.ID, &i.Email, &i.Password)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, first_name, last_name, email, created_at FROM user WHERE id = ?
`

type GetUserByIdRow struct {
	ID        int64
	FirstName string
	LastName  string
	Email     string
	CreatedAt sql.NullString
}

func (q *Queries) GetUserById(ctx context.Context, id int64) (GetUserByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
