// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Signup() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = Head().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html><div id=\"signup-page\"><div id=\"signup-page-left\" class=\"signup-split\"><hr></div><div id=\"signup-page-right\" class=\"signup-split\"><form id=\"signup-form\" name=\"signup\" action=\"/signup\" method=\"POST\"><div style=\"float:left;\"><label for=\"first-name\">First Name</label> <input type=\"text\" name=\"first-name\" placeholder=\"First Name\"></div><div style=\"float:left;\"><label for=\"last-name\">Last Name</label> <input type=\"text\" name=\"last-name\" placeholder=\"Last Name\"></div><br style=\"clear:both;\"><div><label for=\"email\">Email</label> <input type=\"email\" name=\"email\" placeholder=\"Email\"></div><div><label for=\"email-confirm\">Confirm Email</label> <input type=\"email\" name=\"email-confirm\" placeholder=\"Confirm Email\"></div><div><label for=\"password\">Password</label> <input type=\"password\" name=\"password\" placeholder=\"Password\"></div><div><label for=\"password-confirm\">Confirm Password</label> <input type=\"password\" name=\"password-confirm\" placeholder=\"Confirm Password\"></div><div><input type=\"submit\" value=\"Submit\"></div></form></div></div></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
